  - alias : 'Test Automation'
    trigger:
      platform: state
      entity_id: sensor.esp
    # Optional
      to: 'Empty'
    action:
      service: light.turn_on
      data:
        entity_id : light.orb
        brightness: 50
        rgb_color: [255, 0, 0]

  - alias : 'Test Automation2'
    trigger:
      platform: state
      entity_id: sensor.esp
    # Optional
      to: 'Okay'
    action:
      service: light.turn_off
      data:
        entity_id : light.orb

  - alias: "Update Water Sensor"
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.cat_water
    action:
      - service: mqtt.publish
        data_template:
          topic: "interior/indicatorBoard/led/0"
          payload: '{"state":{{ trigger.to_state.state }}}'