homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 40.5585314
  longitude: -82.417327
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1135
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

nest:
  client_id: 4e915c62-d8cd-408f-915b-1b7589c92620
  client_secret: W2IHEdDCTS3SirwwbxFkTJlTB

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
# cloud:

#group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
sensor: !include sensors.yaml
light: !include lights.yaml
switch: !include switches.yaml

zwave:
  usb_path: /dev/zwave

mqtt:
  broker: 192.168.1.18
  username: logan
  password: lakD3c@#

logger:
  default: warning
  logs:
    homeassistant.components.zwave: debug
    homeassistant.components.mqtt: debug


binary_sensor:
  - platform: mqtt
    name: "Cat Water"
    state_topic: "sensors/indoor/catWater"
    value_template: '{{ value_json.state }}'
    device_class: moisture
  - platform: mqtt
    name: "Mailbox"
    state_topic: "sensors/outdoor/mailbox"
    value_template: '{{ value_json.state }}'
    device_class: presence
    # swap the payloads... for reasons
    #payload_on: "OFF"
    #payload_off: "ON"
device_tracker:
  - platform: netgear
    url: 192.168.1.1
    username: admin
    password: 77Shadow77
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
